### ISSUE TITLE
Tailscale 1.36.1 is available

### ISSUE THREAD

**Issue by nshalman** [TritonDataCenter/pkgsrc-extra#1]
Once I get my pkgsrc build zone back into shape hopefully I can open PRs rather than issues, but for now I'll point out that
https://github.com/nshalman/tailscale/releases/tag/v1.36.1-sunos is tagged and the upgrade PR is up for OmniOS: https://github.com/omniosorg/omnios-extra/pull/1242

**Comment by nshalman** [comment]
Updated for 1.36.1

**Comment by jperkin** [comment]
Updated in https://github.com/TritonDataCenter/pkgsrc-extra/commit/73f129cdc1f2f165d889f215c6aed52c134d6e19, thanks!

**Comment by nshalman** [comment]
Thank you!
