### ISSUE TITLE
Tailscale 1.38.4 is available

### ISSUE THREAD

**Issue by nshalman** [TritonDataCenter/pkgsrc-extra#2]
https://github.com/nshalman/tailscale/releases/tag/v1.38.1-sunos
https://github.com/omniosorg/omnios-extra/pull/1259

**Comment by nshalman** [comment]
https://github.com/nshalman/tailscale/releases/tag/v1.38.2-sunos

**Comment by nshalman** [comment]
https://github.com/nshalman/tailscale/releases/tag/v1.38.3-sunos

@jperkin I still haven't had bandwidth to set up a build environment to open a PR... Is this something you can still handle when you have a moment?

**Comment by nshalman** [comment]
https://github.com/nshalman/tailscale/releases/tag/v1.38.4-sunos

**Comment by jperkin** [comment]
Hey! Sorry, I meant to get to this today but ran out of time. Please ping me on Monday if it looks like I didn't get to it again..

**Comment by jperkin** [comment]
Updated in https://github.com/TritonDataCenter/pkgsrc-extra/commit/b7bc4f43f0001d3359acd9abcc6446e8cf187a52, thanks!

**Comment by nshalman** [comment]
Thank you!
